version: "3"
services:
    db:
        container_name: mydb
        image: mysql:8.0
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: LifeHasN0Mean1ng!
    app:
        container_name: python_app
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"